/**
 * Registro central de ações agentic (Trading e operações correlatas)
 *
 * Fonte única de governança para:
 * - endpoint/verbos
 * - nível de risco
 * - necessidade de aprovação
 * - permissões RBAC
 *
 * Documentação em PT-BR (Regra 10 CLAUDE.md).
 */

export type AgenticService =
  | 'trading'
  | 'payments'
  | 'grafana'
  | 'stack_ops'
  | 'agentic_task';

export type AgenticRiskLevel = 'low' | 'medium' | 'high' | 'critical';

export type AgenticApprovalRequirement = 'never' | 'always' | 'risk_based';

export type AgenticActionDefinition = {
  id: string;
  service: AgenticService;
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  riskLevel: AgenticRiskLevel;
  approval: AgenticApprovalRequirement;
  permissions: string[];
  requiredFields?: string[];
  uiCardType: 'read' | 'write' | 'approval' | 'task';
};

const TRADING_READ: AgenticActionDefinition[] = [
  {
    id: 'trading.status',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/status',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.ws_status',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/ws/status',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.intervals',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/intervals',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.symbols',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/symbols',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.symbol_preferences.get',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/symbol-preferences',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.market',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/market/:symbol',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.account',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/account',
    riskLevel: 'medium',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.positions',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/positions',
    riskLevel: 'medium',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.risk_config.get',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/risk-config',
    riskLevel: 'medium',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.signals',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/signals',
    riskLevel: 'medium',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.signals.history',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/signals/history',
    riskLevel: 'medium',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.signals.history.stats',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/signals/history/stats',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.orders',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/orders',
    riskLevel: 'medium',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.orders.history',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/orders/history',
    riskLevel: 'medium',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.stop_orders',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/stop-orders',
    riskLevel: 'medium',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.klines',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/klines/:symbol',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.orderbook',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/orderbook/:symbol',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.funding_rate',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/funding-rate/:symbol',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.mark_price',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/mark-price/:symbol',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.trades',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/trades/:symbol',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.analysis',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/analysis/:symbol',
    riskLevel: 'medium',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.analysis.history',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/analysis/history',
    riskLevel: 'medium',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.validations',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/validations',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.validations.diagnostics',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/validations/diagnostics',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.datasets',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/datasets',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.signal_scheduler.get',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/signal-scheduler',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.analysis_scheduler.get',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/analysis-scheduler',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.news_presets.get',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/news-presets',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.analysis_profile.get',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/analysis-profile',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.arbitrage_catalog',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/arbitrage/catalog',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.control_history',
    service: 'trading',
    method: 'GET',
    path: '/api/integrations/trading/control-history',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
];

const TRADING_WRITE: AgenticActionDefinition[] = [
  {
    id: 'trading.symbol_preferences.put',
    service: 'trading',
    method: 'PUT',
    path: '/api/integrations/trading/symbol-preferences',
    riskLevel: 'medium',
    approval: 'risk_based',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.positions.close',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/positions/:symbol/close',
    riskLevel: 'critical',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.positions.stop',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/positions/:symbol/stop',
    riskLevel: 'critical',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.positions.delete',
    service: 'trading',
    method: 'DELETE',
    path: '/api/integrations/trading/positions',
    riskLevel: 'critical',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.risk_config.put',
    service: 'trading',
    method: 'PUT',
    path: '/api/integrations/trading/risk-config',
    riskLevel: 'high',
    approval: 'always',
    permissions: ['integrations:trading:manage'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.signals.create',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/signals',
    riskLevel: 'high',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.signals.approve',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/signals/:id/approve',
    riskLevel: 'critical',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.signals.reject',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/signals/:id/reject',
    riskLevel: 'high',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.signals.delete',
    service: 'trading',
    method: 'DELETE',
    path: '/api/integrations/trading/signals/:id',
    riskLevel: 'high',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.orders.create',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/orders',
    riskLevel: 'critical',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.orders.review',
    service: 'trading',
    method: 'PATCH',
    path: '/api/integrations/trading/orders/:id/review',
    riskLevel: 'high',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.orders.approve',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/orders/:id/approve',
    riskLevel: 'critical',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.orders.reject',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/orders/:id/reject',
    riskLevel: 'high',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.orders.delete',
    service: 'trading',
    method: 'DELETE',
    path: '/api/integrations/trading/orders/:id',
    riskLevel: 'critical',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.orders.sync',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/orders/sync',
    riskLevel: 'high',
    approval: 'always',
    permissions: ['integrations:trading:manage'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.stop_orders.create',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/stop-orders',
    riskLevel: 'critical',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.stop_orders.delete',
    service: 'trading',
    method: 'DELETE',
    path: '/api/integrations/trading/stop-orders/:id',
    riskLevel: 'critical',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.signals.generate',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/signals/generate',
    riskLevel: 'high',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.datasets.from_signal',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/datasets/from-signal',
    riskLevel: 'high',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.datasets.review',
    service: 'trading',
    method: 'PATCH',
    path: '/api/integrations/trading/datasets/:id/review',
    riskLevel: 'high',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.signal_scheduler.put',
    service: 'trading',
    method: 'PUT',
    path: '/api/integrations/trading/signal-scheduler',
    riskLevel: 'high',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.news_presets.create',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/news-presets',
    riskLevel: 'medium',
    approval: 'risk_based',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.news_presets.update',
    service: 'trading',
    method: 'PUT',
    path: '/api/integrations/trading/news-presets/:id',
    riskLevel: 'medium',
    approval: 'risk_based',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.news_presets.delete',
    service: 'trading',
    method: 'DELETE',
    path: '/api/integrations/trading/news-presets/:id',
    riskLevel: 'medium',
    approval: 'risk_based',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.news_presets.apply',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/news-presets/apply',
    riskLevel: 'medium',
    approval: 'risk_based',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.analysis_profile.put',
    service: 'trading',
    method: 'PUT',
    path: '/api/integrations/trading/analysis-profile',
    riskLevel: 'medium',
    approval: 'risk_based',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.analysis_scheduler.put',
    service: 'trading',
    method: 'PUT',
    path: '/api/integrations/trading/analysis-scheduler',
    riskLevel: 'medium',
    approval: 'risk_based',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.signals.history.delete',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/signals/history/delete',
    riskLevel: 'high',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.signals.history.purge',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/signals/history/purge',
    riskLevel: 'critical',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.orders.history.delete',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/orders/history/delete',
    riskLevel: 'high',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.control',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/control',
    riskLevel: 'critical',
    approval: 'always',
    permissions: ['integrations:trading:manage'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.analysis.history.delete',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/analysis/history/delete',
    riskLevel: 'high',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.analysis.history.purge',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/analysis/history/purge',
    riskLevel: 'critical',
    approval: 'always',
    permissions: ['integrations:trading:write'],
    uiCardType: 'approval',
  },
  {
    id: 'trading.ws.subscribe',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/ws/subscribe',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
  {
    id: 'trading.ws.unsubscribe',
    service: 'trading',
    method: 'POST',
    path: '/api/integrations/trading/ws/unsubscribe',
    riskLevel: 'low',
    approval: 'never',
    permissions: ['integrations:trading:read'],
    uiCardType: 'read',
  },
];

export const AGENTIC_ACTION_REGISTRY: AgenticActionDefinition[] = [
  ...TRADING_READ,
  ...TRADING_WRITE,
];

export function getAgenticActionById(actionId: string): AgenticActionDefinition | undefined {
  return AGENTIC_ACTION_REGISTRY.find((item) => item.id === actionId);
}

export function listAgenticActionsByService(service: AgenticService): AgenticActionDefinition[] {
  return AGENTIC_ACTION_REGISTRY.filter((item) => item.service === service);
}
