import type { ComponentProps } from 'react';
import { OcoOrderForm } from './OcoOrderForm';
import { TradingAccountTabContent } from './TradingAccountTabContent';
import { TradingAnalysisTabContent } from './TradingAnalysisTabContent';
import { TradingChartTabContent } from './TradingChartTabContent';
import { TradingControlTabContent } from './TradingControlTabContent';
import { TradingDialogsSection } from './TradingDialogsSection';
import { TradingHistoryTabContent } from './TradingHistoryTabContent';
import { TradingLabTabContent } from './TradingLabTabContent';
import { TradingNewOrderDialog } from './TradingNewOrderDialog';
import { TradingNewSignalDialog } from './TradingNewSignalDialog';
import { TradingHeaderSection } from './TradingHeaderSection';
import { TradingOperationalAlerts } from './TradingOperationalAlerts';
import { TradingOperationalTabsSection } from './TradingOperationalTabsSection';
import { TradingOrdersTabContent } from './TradingOrdersTabContent';
import { TradingOverviewTabContent } from './TradingOverviewTabContent';
import { TradingOrderBookTabContent } from './TradingOrderBookTabContent';
import { TradingPostmortemTrainingDialog } from './TradingPostmortemTrainingDialog';
import { TradingPostMortemsTabContent } from './TradingPostMortemsTabContent';
import { TradingPortfolioAutoTabContent } from './TradingPortfolioAutoTabContent';
import { TradingPositionsTabContent } from './TradingPositionsTabContent';
import { TradingPrimaryTabsSection } from './TradingPrimaryTabsSection';
import { TradingReviewOrderDialog } from './TradingReviewOrderDialog';
import { TradingRiskConfigDialog } from './TradingRiskConfigDialog';
import { TradingSignalsAutoTabContent } from './TradingSignalsAutoTabContent';
import { TradingSignalsTabContent } from './TradingSignalsTabContent';
import { TradingStatsPrimaryRow, TradingStatsSecondaryRow } from './TradingStatsRows';
import { TradingTabsShell } from './TradingTabsShell';

export type AccountTabProps = ComponentProps<typeof TradingAccountTabContent>;
export type AnalysisTabProps = ComponentProps<typeof TradingAnalysisTabContent>;
export type ChartTabProps = ComponentProps<typeof TradingChartTabContent>;
export type ControlTabProps = ComponentProps<typeof TradingControlTabContent>;
export type LabTabProps = ComponentProps<typeof TradingLabTabContent>;
export type HistoryTabProps = ComponentProps<typeof TradingHistoryTabContent>;
export type OrdersTabProps = ComponentProps<typeof TradingOrdersTabContent>;
export type OrderBookTabProps = ComponentProps<typeof TradingOrderBookTabContent>;
export type OverviewTabProps = ComponentProps<typeof TradingOverviewTabContent>;
export type PostMortemsTabProps = ComponentProps<typeof TradingPostMortemsTabContent>;
export type PortfolioAutoTabProps = ComponentProps<typeof TradingPortfolioAutoTabContent>;
export type PositionsTabProps = ComponentProps<typeof TradingPositionsTabContent>;
export type PrimaryTabsSectionProps = ComponentProps<typeof TradingPrimaryTabsSection>;
export type SignalsAutoTabProps = ComponentProps<typeof TradingSignalsAutoTabContent>;
export type SignalsTabProps = ComponentProps<typeof TradingSignalsTabContent>;
export type HeaderSectionProps = ComponentProps<typeof TradingHeaderSection>;
export type OperationalAlertsSectionProps = ComponentProps<typeof TradingOperationalAlerts>;
export type OperationalTabsSectionProps = ComponentProps<typeof TradingOperationalTabsSection>;
export type StatsPrimarySectionProps = ComponentProps<typeof TradingStatsPrimaryRow>;
export type StatsSecondarySectionProps = ComponentProps<typeof TradingStatsSecondaryRow>;
export type TabsShellSectionProps = Omit<ComponentProps<typeof TradingTabsShell>, 'children'>;

export type NewOrderDialogProps = ComponentProps<typeof TradingNewOrderDialog>;
export type OcoOrderDialogProps = ComponentProps<typeof OcoOrderForm>;
export type ReviewOrderDialogProps = ComponentProps<typeof TradingReviewOrderDialog>;
export type RiskConfigDialogProps = ComponentProps<typeof TradingRiskConfigDialog>;
export type PostmortemTrainingDialogProps = ComponentProps<typeof TradingPostmortemTrainingDialog>;
export type NewSignalDialogProps = ComponentProps<typeof TradingNewSignalDialog>;
export type DialogsSectionProps = ComponentProps<typeof TradingDialogsSection>;
