import { z } from 'zod';

export const TRADING_LLM_CITED_VALUES_SCHEMA = z.object({
  rsi: z.number().optional(),
  macdLine: z.number().optional(),
  macdSignal: z.number().optional(),
  macdHistogram: z.number().optional(),
  ema9: z.number().optional(),
  ema21: z.number().optional(),
  ema50: z.number().optional(),
  ema200: z.number().optional(),
  sma20: z.number().optional(),
  sma50: z.number().optional(),
  sma200: z.number().optional(),
  bollingerUpper: z.number().optional(),
  bollingerMiddle: z.number().optional(),
  bollingerLower: z.number().optional(),
  bollingerPercentB: z.number().optional(),
  atrValue: z.number().optional(),
  atrPercentage: z.number().optional(),
  stochasticK: z.number().optional(),
  stochasticD: z.number().optional(),
  adxValue: z.number().optional(),
  pivotPoint: z.number().optional(),
  resistance1: z.number().optional(),
  resistance2: z.number().optional(),
  resistance3: z.number().optional(),
  support1: z.number().optional(),
  support2: z.number().optional(),
  support3: z.number().optional(),
  volumeRatio: z.number().optional(),
  currentPrice: z.number().optional(),
}).partial().default({});

const TRADING_OPERATION_TYPE_ZOD = z.enum(['scalping', 'swing', 'position', 'cash_and_carry', 'arbitrage', 'hedge', 'neutral']);

export const TRADING_LLM_SIGNAL_SCHEMA = z.object({
  signalType: z.enum(['entry_long', 'entry_short', 'exit', 'adjust_sl', 'adjust_tp', 'hold', 'neutral']),
  operationType: TRADING_OPERATION_TYPE_ZOD,
  expectedDurationMinutes: z.number().int().min(0).max(43200),
  confidence: z.number().min(0).max(1),
  tradeSummary: z.string().min(1),
  motivators: z.array(z.string().min(2)).min(1),
  invalidationReasons: z.array(z.string().min(2)).min(1),
  reasoning: z.string().min(10),
  timeframeUsed: z.string().optional(),
  citedValues: TRADING_LLM_CITED_VALUES_SCHEMA,
  suggestedPrice: z.number().positive().optional(),
  suggestedStopLoss: z.number().positive().optional(),
  suggestedTakeProfit: z.number().positive().optional(),
  suggestedSize: z.number().positive().optional(),
  riskReward: z.number().positive().optional(),
  marketCondition: z.string().min(3).optional(),
  riskScore: z.number().min(0).max(100).optional(),
});

export const TRADING_LLM_SIGNAL_JSON_SCHEMA = {
  name: 'trading_llm_signal',
  schema: {
    type: 'object' as const,
    additionalProperties: false,
    required: [
      'signalType',
      'operationType',
      'expectedDurationMinutes',
      'confidence',
      'tradeSummary',
      'motivators',
      'invalidationReasons',
      'reasoning',
      'citedValues',
    ],
    properties: {
      signalType: {
        type: 'string' as const,
        enum: ['entry_long', 'entry_short', 'exit', 'adjust_sl', 'adjust_tp', 'hold', 'neutral'],
      },
      operationType: {
        type: 'string' as const,
        enum: ['scalping', 'swing', 'position', 'cash_and_carry', 'arbitrage', 'hedge', 'neutral'],
      },
      expectedDurationMinutes: { type: 'integer' as const },
      confidence: { type: 'number' as const },
      tradeSummary: { type: 'string' as const },
      motivators: { type: 'array' as const, items: { type: 'string' as const } },
      invalidationReasons: { type: 'array' as const, items: { type: 'string' as const } },
      reasoning: { type: 'string' as const },
      timeframeUsed: { type: 'string' as const },
      citedValues: {
        type: 'object' as const,
        additionalProperties: false,
        properties: {
          rsi: { type: 'number' as const },
          macdLine: { type: 'number' as const },
          macdSignal: { type: 'number' as const },
          macdHistogram: { type: 'number' as const },
          ema9: { type: 'number' as const },
          ema21: { type: 'number' as const },
          ema50: { type: 'number' as const },
          ema200: { type: 'number' as const },
          sma20: { type: 'number' as const },
          sma50: { type: 'number' as const },
          sma200: { type: 'number' as const },
          bollingerUpper: { type: 'number' as const },
          bollingerMiddle: { type: 'number' as const },
          bollingerLower: { type: 'number' as const },
          bollingerPercentB: { type: 'number' as const },
          atrValue: { type: 'number' as const },
          atrPercentage: { type: 'number' as const },
          stochasticK: { type: 'number' as const },
          stochasticD: { type: 'number' as const },
          adxValue: { type: 'number' as const },
          pivotPoint: { type: 'number' as const },
          resistance1: { type: 'number' as const },
          resistance2: { type: 'number' as const },
          resistance3: { type: 'number' as const },
          support1: { type: 'number' as const },
          support2: { type: 'number' as const },
          support3: { type: 'number' as const },
          volumeRatio: { type: 'number' as const },
          currentPrice: { type: 'number' as const },
        },
      },
      suggestedPrice: { type: 'number' as const },
      suggestedStopLoss: { type: 'number' as const },
      suggestedTakeProfit: { type: 'number' as const },
      suggestedSize: { type: 'number' as const },
      riskReward: { type: 'number' as const },
      marketCondition: { type: 'string' as const },
      riskScore: { type: 'number' as const },
    },
  },
};

export const TRADING_LLM_SIGNAL_PARTIAL_SCHEMA = z.object({
  signalType: z.enum(['entry_long', 'entry_short', 'exit', 'adjust_sl', 'adjust_tp', 'hold', 'neutral']).optional(),
  operationType: TRADING_OPERATION_TYPE_ZOD.optional(),
  expectedDurationMinutes: z.number().int().min(0).max(43200).optional(),
  confidence: z.number().min(0).max(1).optional(),
  tradeSummary: z.string().optional(),
  motivators: z.array(z.string().min(2)).optional(),
  invalidationReasons: z.array(z.string().min(2)).optional(),
  reasoning: z.string().min(5).optional(),
  timeframeUsed: z.string().optional(),
  citedValues: TRADING_LLM_CITED_VALUES_SCHEMA,
  suggestedPrice: z.number().positive().nullable().optional(),
  suggestedStopLoss: z.number().positive().nullable().optional(),
  suggestedTakeProfit: z.number().positive().nullable().optional(),
  suggestedSize: z.number().positive().nullable().optional(),
  riskReward: z.number().positive().nullable().optional(),
  marketCondition: z.string().optional(),
  riskScore: z.number().min(0).max(100).optional(),
});

export type TradingLlmSignal = z.infer<typeof TRADING_LLM_SIGNAL_SCHEMA>;
export type TradingLlmSignalPartial = z.infer<typeof TRADING_LLM_SIGNAL_PARTIAL_SCHEMA>;
