import { useWiseAccountCardDisputeMutations } from './use-wise-account-card-dispute-mutations';
import { useWiseAccountCardOrderActionHandlers } from './use-wise-account-card-order-action-handlers';
import { useWiseDisputeKycActionHandlers } from './use-wise-dispute-kyc-action-handlers';
import { useWiseAccountCardDisputeState } from './use-wise-account-card-dispute-state';
import type {
  UseWiseAccountCardDisputeActionsOptions,
  UseWiseAccountCardDisputeActionsResult,
} from './wise-account-card-dispute-types';

export function useWiseAccountCardDisputeActions(
  options: UseWiseAccountCardDisputeActionsOptions,
): UseWiseAccountCardDisputeActionsResult {
  const {
    disputeUpload,
    kycUploadAdditional,
    kycUploadDocument,
    notify,
    parseJsonSafe,
    profileFilter,
    t,
  } = options;

  const {
    accountDetailsPayload,
    accountDetailsResponse,
    cardOrderAvailability,
    cardOrderDetails,
    cardOrderId,
    cardOrderPayload,
    cardOrderPinPayload,
    cardOrderRequirements,
    cardOrderStatusPayload,
    cardOrderValidationPayload,
    cardTransactionDetails,
    cardTransactionId,
    disputeFlowForm,
    disputeFlowStepResult,
    disputeFlowSubmitResult,
    disputeStatusUpdate,
    kycRequiredEvidences,
    setAccountDetailsPayload,
    setAccountDetailsResponse,
    setCardOrderAvailability,
    setCardOrderDetails,
    setCardOrderId,
    setCardOrderPayload,
    setCardOrderPinPayload,
    setCardOrderRequirements,
    setCardOrderStatusPayload,
    setCardOrderValidationPayload,
    setCardTransactionDetails,
    setCardTransactionId,
    setDisputeFlowForm,
    setDisputeFlowStepResult,
    setDisputeFlowSubmitResult,
    setDisputeStatusUpdate,
    setKycRequiredEvidences,
  } = useWiseAccountCardDisputeState();

  const {
    createAccountDetailsOrderMutation,
    createCardOrderMutation,
    disputeFlowStepMutation,
    disputeFlowSubmitMutation,
    getCardOrderAvailabilityMutation,
    getCardOrderDetailsMutation,
    getCardOrderRequirementsMutation,
    getCardTransactionMutation,
    getKycRequiredEvidencesMutation,
    presetCardOrderPinMutation,
    updateCardOrderStatusMutation,
    updateDisputeStatusMutation,
    uploadDisputeFileMutation,
    uploadKycAdditionalMutation,
    uploadKycDocumentMutation,
    validateCardOrderAddressMutation,
  } = useWiseAccountCardDisputeMutations({
    disputeUpload,
    kycUploadAdditional,
    kycUploadDocument,
    notify,
    profileFilter,
    setAccountDetailsResponse,
    setCardOrderAvailability,
    setCardOrderDetails,
    setCardOrderRequirements,
    setCardTransactionDetails,
    setDisputeFlowStepResult,
    setDisputeFlowSubmitResult,
    setKycRequiredEvidences,
    t,
  });

  const {
    handleCreateAccountDetailsOrder,
    handleCreateCardOrder,
    handleFetchCardOrderAvailability,
    handleFetchCardOrderDetails,
    handleFetchCardOrderRequirements,
    handleFetchCardTransaction,
    handlePresetCardOrderPin,
    handleUpdateCardOrderStatus,
    handleValidateCardOrderAddress,
  } = useWiseAccountCardOrderActionHandlers({
    accountDetailsPayload,
    cardOrderId,
    cardOrderPayload,
    cardOrderPinPayload,
    cardOrderStatusPayload,
    cardOrderValidationPayload,
    cardTransactionId,
    createAccountDetailsOrderMutation,
    createCardOrderMutation,
    getCardOrderAvailabilityMutation,
    getCardOrderDetailsMutation,
    getCardOrderRequirementsMutation,
    getCardTransactionMutation,
    notify,
    parseJsonSafe,
    presetCardOrderPinMutation,
    t,
    updateCardOrderStatusMutation,
    validateCardOrderAddressMutation,
  });

  const {
    handleDisputeFileUpload,
    handleDisputeFlowStep,
    handleDisputeFlowSubmit,
    handleFetchKycEvidences,
    handleUpdateDisputeStatus,
    handleUploadKycAdditional,
    handleUploadKycDocument,
  } = useWiseDisputeKycActionHandlers({
    disputeFlowForm,
    disputeFlowStepMutation,
    disputeFlowSubmitMutation,
    disputeStatusUpdate,
    disputeUpload,
    getKycRequiredEvidencesMutation,
    kycUploadAdditional,
    kycUploadDocument,
    notify,
    parseJsonSafe,
    t,
    updateDisputeStatusMutation,
    uploadDisputeFileMutation,
    uploadKycAdditionalMutation,
    uploadKycDocumentMutation,
  });

  return {
    accountDetailsPayload,
    accountDetailsResponse,
    cardOrderAvailability,
    cardOrderDetails,
    cardOrderId,
    cardOrderPayload,
    cardOrderPinPayload,
    cardOrderRequirements,
    cardOrderStatusPayload,
    cardOrderValidationPayload,
    cardTransactionDetails,
    cardTransactionId,
    disputeFlowForm,
    disputeFlowStepResult,
    disputeFlowSubmitResult,
    disputeStatusUpdate,
    handleCreateAccountDetailsOrder,
    handleCreateCardOrder,
    handleDisputeFlowStep,
    handleDisputeFlowSubmit,
    handleDisputeFileUpload,
    handleFetchCardOrderAvailability,
    handleFetchCardOrderDetails,
    handleFetchCardOrderRequirements,
    handleFetchCardTransaction,
    handleFetchKycEvidences,
    handlePresetCardOrderPin,
    handleUpdateCardOrderStatus,
    handleUpdateDisputeStatus,
    handleUploadKycAdditional,
    handleUploadKycDocument,
    handleValidateCardOrderAddress,
    isPendingCardOrderAvailability: getCardOrderAvailabilityMutation.isPending,
    isPendingCardOrderCreate: createCardOrderMutation.isPending,
    isPendingCardOrderPin: presetCardOrderPinMutation.isPending,
    isPendingCardOrderStatusUpdate: updateCardOrderStatusMutation.isPending,
    isPendingCardOrderValidateAddress: validateCardOrderAddressMutation.isPending,
    isPendingCardTransactionFetch: getCardTransactionMutation.isPending,
    isPendingCreateAccountDetailsOrder: createAccountDetailsOrderMutation.isPending,
    isPendingDisputeFileUpload: uploadDisputeFileMutation.isPending,
    isPendingDisputeFlowStep: disputeFlowStepMutation.isPending,
    isPendingDisputeFlowSubmit: disputeFlowSubmitMutation.isPending,
    isPendingDisputeStatusUpdate: updateDisputeStatusMutation.isPending,
    isPendingFetchKycEvidences: getKycRequiredEvidencesMutation.isPending,
    isPendingUploadKycAdditional: uploadKycAdditionalMutation.isPending,
    isPendingUploadKycDocument: uploadKycDocumentMutation.isPending,
    kycRequiredEvidences,
    setAccountDetailsPayload,
    setCardOrderId,
    setCardOrderPayload,
    setCardOrderPinPayload,
    setCardOrderStatusPayload,
    setCardOrderValidationPayload,
    setCardTransactionId,
    setDisputeFlowForm,
    setDisputeStatusUpdate,
  };
}
